/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

/**
 *
 * @author onair
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRanger = new javax.swing.JButton();
        btnEdge = new javax.swing.JButton();
        btnEco = new javax.swing.JButton();
        btnMustang = new javax.swing.JButton();
        btnLobo = new javax.swing.JButton();
        btnFigo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtFinal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbPago = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RANGER.jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(840, 300, 330, 180);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EDGE.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(460, 300, 320, 170);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MUSTANG.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(840, 50, 320, 170);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ECOSPORT.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 300, 320, 170);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FIGO.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 40, 320, 170);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOBORAP.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(450, 50, 320, 170);

        btnRanger.setText("RANGER 2020");
        btnRanger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionRanger(evt);
            }
        });
        jPanel1.add(btnRanger);
        btnRanger.setBounds(920, 480, 180, 40);

        btnEdge.setText("EDGE 2020");
        btnEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionEdge(evt);
            }
        });
        jPanel1.add(btnEdge);
        btnEdge.setBounds(540, 480, 180, 40);

        btnEco.setText("ECOSPORT 2020");
        btnEco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionEco(evt);
            }
        });
        jPanel1.add(btnEco);
        btnEco.setBounds(120, 480, 180, 40);

        btnMustang.setText("MUSTANG 2020");
        btnMustang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionMustang(evt);
            }
        });
        jPanel1.add(btnMustang);
        btnMustang.setBounds(920, 230, 180, 40);

        btnLobo.setText("LOBO RAP 2020");
        btnLobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionLobo(evt);
            }
        });
        jPanel1.add(btnLobo);
        btnLobo.setBounds(530, 230, 180, 40);

        btnFigo.setText("FIGO 2020");
        btnFigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionFigo(evt);
            }
        });
        jPanel1.add(btnFigo);
        btnFigo.setBounds(130, 230, 180, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fo.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 550);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel8.setText("MODELO:");

        jLabel9.setText("COSTO:");

        jLabel10.setText("COSTO FINAL:");

        jLabel11.setText("METODO DE PAGO:");

        cmbPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EFECTIVO", "TARJETA" }));
        cmbPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(cmbPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(83, 83, 83))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cmbPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPagoActionPerformed

    private void seleccionFigo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionFigo
        // TODO add your handling code here:
        carro = carro.FIGO_2020;
        mp();
        fi = carro.calcularCostofinal(c);
        colocarTexto();
    }//GEN-LAST:event_seleccionFigo

    private void seleccionLobo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionLobo
        // TODO add your handling code here:
        carro = carro.LOBO_2020;
        mp();
        fi = carro.calcularCostofinal(c);
        colocarTexto();
    }//GEN-LAST:event_seleccionLobo

    private void seleccionMustang(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionMustang
        // TODO add your handling code here:
        carro = carro.MUSTANG_2020;
        mp();
        fi = carro.calcularCostofinal(c);
        colocarTexto();
    }//GEN-LAST:event_seleccionMustang

    private void seleccionEco(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionEco
        // TODO add your handling code here:
        carro = carro.ECOSPORT_2020;
        mp();
        fi = carro.calcularCostofinal(c);
        colocarTexto();
    }//GEN-LAST:event_seleccionEco

    private void seleccionEdge(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionEdge
        // TODO add your handling code here:
        carro = carro.EDGE_2020;
        mp();
        fi = carro.calcularCostofinal(c);
        colocarTexto();
    }//GEN-LAST:event_seleccionEdge

    private void seleccionRanger(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionRanger
        // TODO add your handling code here:
        carro = carro.RANGER_2020;
        mp();
        fi = carro.calcularCostofinal(c);
        colocarTexto();
    }//GEN-LAST:event_seleccionRanger

    Carros carro; //Se crea el objeto de tipo Carros.
    
    public int c; //Esta variable sera la que dicte el tipo de pago.
    
    public double fi; //Esta variable sera el precio final del automovil.
    
    private void colocarTexto() { //Metodo creado para ahorrar codigo a la hora de imprimir.
        
        txtModelo.setText(carro.toString());
        txtCosto.setText(String.valueOf(carro.costo));
        txtFinal.setText(Double.toString(fi));
        
    }
    
    public int mp() { //Metodo creado para asignar a la variable designada para el metodo de pago una opcion viable.
        
        String lectura = (String)cmbPago.getSelectedItem();
        
        if(lectura == "EFECTIVO") {
            
            c = 0;
            
        } else {
            
            c = 1;
            
        }
        
        return c;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEco;
    private javax.swing.JButton btnEdge;
    private javax.swing.JButton btnFigo;
    private javax.swing.JButton btnLobo;
    private javax.swing.JButton btnMustang;
    private javax.swing.JButton btnRanger;
    private javax.swing.JComboBox<String> cmbPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtFinal;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
